//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AlmacenDto {
    id?: number;
    codigoAlmacen?: string | undefined;
    dirrecion?: string | undefined;
    nombreAlmacen?: string | undefined;
}

export interface AsientoCreateDto {
    tipoAsiento?: TipoAsientoCreateDto[] | undefined;
    planCuenta?: PlanCuentaCreateDto[] | undefined;
    rol?: RolAsientoDTO[] | undefined;
}

export interface AsientoCreateDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: AsientoCreateDto;
}

export interface AsientoDto {
    id?: number;
    nombreAsiento?: string | undefined;
    tipoAsientoId?: number;
    nombretipoAsiento?: string | undefined;
    cuentas?: CuentasDto[] | undefined;
}

export interface AsientoEditar {
    id?: number;
    nombreAsiento?: string | undefined;
    tipoAsiento?: TipoAsientoDto;
    planCuentas?: VPlanCuentas[] | undefined;
    rolAsiento?: RolAsientoDTO;
}

export interface AsientoEditarDto {
    asientoEditar?: AsientoEditar;
    asientocreate?: AsientoCreateDto;
}

export interface AsientoEditarDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: AsientoEditarDto;
}

export interface AtributoDto {
    categoriaId?: number;
    atributoId?: number;
    etiqueta?: string | undefined;
    tipo?: string | undefined;
}

export interface AtributoDtoListResponse {
    status?: number;
    message?: string | undefined;
    data?: AtributoDto[] | undefined;
}

export interface AtributosDto {
    atributoId?: number;
    valor?: string | undefined;
}

export interface AutenticacionDto {
    usuario?: string | undefined;
    password?: string | undefined;
}

export interface BooleanNullableResponse {
    status?: number;
    message?: string | undefined;
    data?: boolean | undefined;
}

export interface BooleanResponse {
    status?: number;
    message?: string | undefined;
    data?: boolean;
}

export interface Categoria {
    categoriaId?: number;
    nombre?: string | undefined;
    izq?: number;
    der?: number;
    productoMaestro?: ProductoMaestro;
}

export interface CategoriaDto {
    categoriaId?: number;
    nombre?: string | undefined;
    izq?: number;
    der?: number;
}

export interface CategoriaInsertarV {
    categoriaId?: number;
    nombre?: string | undefined;
}

export interface CategoriaModificarDto {
    categoriaId?: number;
    nombre?: string | undefined;
}

export interface CategoriaNodo {
    categoriaId?: number;
    nombre?: string | undefined;
    izq?: number;
    der?: number;
    profundidad?: number;
    hijos?: CategoriaNodo[] | undefined;
}

export interface CategoriaNodoListResponse {
    status?: number;
    message?: string | undefined;
    data?: CategoriaNodo[] | undefined;
}

export interface ClienteDto {
    id?: number;
    numeroDocumento?: string | undefined;
    codigoCliente?: string | undefined;
    nombreCompletoCliente?: string | undefined;
    correoElectronico?: string | undefined;
    dirrecion?: string | undefined;
    telefono?: string | undefined;
    codigoTipoDocumentoIdentidad?: number;
    complemento?: string | undefined;
    tipoDocumentoIdentidad?: ParametrosDto;
}

export interface ClienteDtoListResponse {
    status?: number;
    message?: string | undefined;
    data?: ClienteDto[] | undefined;
}

export interface ClienteDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: ClienteDto;
}

export interface CreateProveedorDto {
    codigo?: string | undefined;
    monedas?: VMoneda[] | undefined;
    planCuentas?: VPlanCuentas[] | undefined;
}

export interface CreateProveedorDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: CreateProveedorDto;
}

export interface DetalleAlmacen {
    detallealmacenid?: number;
    ordencompraproductoId?: number;
    almacenid?: number;
    fechatransacion?: Date;
    fecharegistro?: Date;
    serieid?: number;
    estadoVendido?: number;
}

export interface DetalleAlmacenListResponse {
    status?: number;
    message?: string | undefined;
    data?: DetalleAlmacen[] | undefined;
}

export interface DetalleAlmacenResponse {
    status?: number;
    message?: string | undefined;
    data?: DetalleAlmacen;
}

export interface DetalleProducto {
    cantidad?: number;
    codigoProducto?: string | undefined;
    ordenCompraProductoId?: number;
    fechaVencimiento?: Date;
    productoId?: number;
    lote?: string | undefined;
    almacen?: AlmacenDto;
    nombreAlmacen?: string | undefined;
    nombreProducto?: string | undefined;
    precioCompra?: number;
    precioTotal?: number;
}

export interface EditarDto {
    proveedor?: any | undefined;
    monedas?: VMoneda[] | undefined;
    planCuentas?: VPlanCuentas[] | undefined;
}

export interface EditarDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: EditarDto;
}

export interface EstadoVenta {
    id?: number;
    nombreEstadoVenta?: string | undefined;
}

export interface GeneracionCodigo {
    codigo?: string | undefined;
    nivel?: number;
}

export interface GeneracionCodigoResponse {
    status?: number;
    message?: string | undefined;
    data?: GeneracionCodigo;
}

export interface GeneralDto {
    id?: number;
    nombreEmpresa?: string | undefined;
    direccion?: string | undefined;
    usuario_id?: number;
    nombrePropietario?: string | undefined;
    email?: string | undefined;
    telefono?: string | undefined;
    dominio?: string | undefined;
    facturacion?: number;
}

export interface GeneralDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: GeneralDto;
}

export interface Int32NullableResponse {
    status?: number;
    message?: string | undefined;
    data?: number | undefined;
}

export interface ListaAsientoDto {
    tipoAsientoId?: number;
    asientoId?: number;
    nombreTipoAsiento?: string | undefined;
    nombreAsiento?: string | undefined;
}

export interface ListaAsientoDtoListResponse {
    status?: number;
    message?: string | undefined;
    data?: ListaAsientoDto[] | undefined;
}

export interface MovimientoCuentas {
    asientoId?: number;
    codigo?: string | undefined;
    fecha?: Date;
    descripcion?: string | undefined;
    para?: string | undefined;
    total?: number;
    metodoPago?: string | undefined;
    realizado?: string | undefined;
    planCuentaId?: number;
    codigoCuenta?: string | undefined;
    nombreCuenta?: string | undefined;
    debe?: number;
    haber?: number;
}

export interface MovimientoCuentasListResponse {
    status?: number;
    message?: string | undefined;
    data?: MovimientoCuentas[] | undefined;
}

export interface MovimientoGeneralCuentaDto {
    codigo?: string | undefined;
    asientoId?: number;
}

export interface MovimientoGenerales {
    asientoId?: number;
    codigo?: string | undefined;
    fecha?: Date;
    descripcion?: string | undefined;
    para?: string | undefined;
    total?: number;
    metodoPago?: string | undefined;
    realizado?: string | undefined;
}

export interface MovimientoGeneralesListResponse {
    status?: number;
    message?: string | undefined;
    data?: MovimientoGenerales[] | undefined;
}

export interface ObjectListResponse {
    status?: number;
    message?: string | undefined;
    data?: any[] | undefined;
}

export interface ObjectResponse {
    status?: number;
    message?: string | undefined;
    data?: any | undefined;
}

export interface ObtenerTipoAsiento {
    codigo?: string | undefined;
    nombreCuenta?: string | undefined;
    rol?: string | undefined;
    planCuentaId?: number;
    id?: number;
}

export interface ObtenerTipoAsientoListResponse {
    status?: number;
    message?: string | undefined;
    data?: ObtenerTipoAsiento[] | undefined;
}

export interface OrdenCompraAlmacenDto {
    id?: number;
    fecha?: Date;
    descripcion?: string | undefined;
    codigoOrden?: string | undefined;
    telefono?: string | undefined;
    nit?: string | undefined;
    proveedor?: ProveedorDto;
    montoliteral?: string | undefined;
    stockActual?: number;
    total?: number;
    estadoId?: number;
    asiento?: ListaAsientoDto;
    usuario?: UsuarioDto;
    productos?: DetalleProducto[] | undefined;
    nombreUsuario?: string | undefined;
}

export interface OrdenCompraDto {
    id?: number;
    fecha?: Date;
    descripcion?: string | undefined;
    codigoOrden?: string | undefined;
    telefono?: string | undefined;
    nit?: string | undefined;
    proveedor?: ProveedorDto;
    montoliteral?: string | undefined;
    stockActual?: number;
    total?: number;
    estadoId?: number;
    asiento?: ListaAsientoDto;
    usuario?: UsuarioDto;
    productos?: OrdenCompraProductoDto[] | undefined;
    nombreUsuario?: string | undefined;
}

export interface OrdenCompraDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: OrdenCompraDto;
}

export interface OrdenCompraProductoDto {
    productoId?: number;
    cantidad?: number;
    codigoProducto?: string | undefined;
    nombreProducto?: string | undefined;
    precioCompra?: number;
    precioTotal?: number;
}

export interface ParametrosDto {
    id?: number;
    codigoClasificador?: string | undefined;
    codigoTipoParametro?: string | undefined;
    descripcion?: string | undefined;
}

export interface Permiso {
    permisoId?: number;
    nombre?: string | undefined;
    ruta?: string | undefined;
    roles?: Rol[] | undefined;
}

export interface PermisoDto {
    permisoId?: number;
    nombre?: string | undefined;
    ruta?: string | undefined;
}

export interface PermisoListResponse {
    status?: number;
    message?: string | undefined;
    data?: Permiso[] | undefined;
}

export interface PersonaCrearDto {
    nombre?: string | undefined;
    apellido?: string | undefined;
    direccion?: string | undefined;
    fechaNacimiento?: Date;
    email?: string | undefined;
    telefono?: string | undefined;
    ci?: string | undefined;
}

export interface PersonaDto {
    personaId?: number;
    nombre?: string | undefined;
    apellido?: string | undefined;
    direccion?: string | undefined;
    fechaNacimiento?: Date;
    email?: string | undefined;
    telefono?: string | undefined;
    ci?: string | undefined;
}

export interface PersonaDtoListResponse {
    status?: number;
    message?: string | undefined;
    data?: PersonaDto[] | undefined;
}

export interface PersonaDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: PersonaDto;
}

export interface PlanCuentaCreateDto {
    id?: number;
    nombreCuenta?: string | undefined;
    codigo?: string | undefined;
}

export interface ProcesarPagoDto {
    fecha?: Date;
}

export interface ProductoCreateDto {
    codigoProducto?: string | undefined;
    proveedores?: VProveedor[] | undefined;
    categorias?: CategoriaNodo[] | undefined;
    productosMaestros?: ProductoMaestroDto[] | undefined;
}

export interface ProductoCreateDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: ProductoCreateDto;
}

export interface ProductoDto {
    productoId?: number;
    codigoProducto?: string | undefined;
    codigoBarra?: string | undefined;
    nombreProducto?: string | undefined;
    stockActual?: number;
    precioCompra?: number;
    utilidadMin?: number;
    precioVentaMin?: number;
    utilidadMax?: number;
    precioVentaMax?: number;
    categoria?: CategoriaDto;
    productoMaestro?: ProductoMaestroDto;
    productoMaestroNombre?: string | undefined;
    imagenes?: string[] | undefined;
    atributos?: AtributosDto[] | undefined;
}

export interface ProductoDtoListResponse {
    status?: number;
    message?: string | undefined;
    data?: ProductoDto[] | undefined;
}

export interface ProductoEditarDto {
    producto?: ProductoDto;
    imagenes?: string[] | undefined;
    categorias?: CategoriaNodo[] | undefined;
    productosMaestros?: ProductoMaestro[] | undefined;
}

export interface ProductoEditarDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: ProductoEditarDto;
}

export interface ProductoMaestro {
    productoMaestroId?: number;
    nombre?: string | undefined;
    categoriaId?: number;
    categoria?: Categoria;
}

export interface ProductoMaestroDto {
    productoMaestroId?: number;
    nombre?: string | undefined;
    categoriaId?: number;
}

export interface ProveedorDto {
    id?: number;
    nit?: string | undefined;
    codigoProveedor?: string | undefined;
    nombreProveedor?: string | undefined;
    dirrecion?: string | undefined;
    contacto?: string | undefined;
    telefono?: number;
    planCuentaId?: number;
}

export interface Rol {
    rolId?: number;
    nombre?: string | undefined;
    permisos?: Permiso[] | undefined;
}

export interface RolAsientoDTO {
    id?: string | undefined;
    rol?: string | undefined;
}

export interface RolCrearDto {
    nombre?: string | undefined;
    permisos?: number[] | undefined;
}

export interface RolCreateDto {
    permisos?: PermisoDto[] | undefined;
}

export interface RolCreateDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: RolCreateDto;
}

export interface RolDto {
    rolId?: number;
    nombre?: string | undefined;
    permisos?: PermisoDto[] | undefined;
}

export interface RolDtoListResponse {
    status?: number;
    message?: string | undefined;
    data?: RolDto[] | undefined;
}

export interface RolDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: RolDto;
}

export interface RolModificarDto {
    rolId?: number;
    nombre?: string | undefined;
    permisos?: number[] | undefined;
}

export interface RolesMostrarModificarDto {
    permisosRol?: RolDto;
    permisos?: PermisoDto[] | undefined;
}

export interface RolesMostrarModificarDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: RolesMostrarModificarDto;
}

export interface StringResponse {
    status?: number;
    message?: string | undefined;
    data?: string | undefined;
}

export interface TipoAsiento {
    id?: number;
    nombreTipoAsiento?: string | undefined;
}

export interface TipoAsientoCreateDto {
    id?: number;
    nombreTipoAsiento?: string | undefined;
}

export interface TipoAsientoDto {
    id?: number;
    nombreTipoAsiento?: string | undefined;
}

export interface TipoAsientoListResponse {
    status?: number;
    message?: string | undefined;
    data?: TipoAsiento[] | undefined;
}

export interface TipoAsientoResponse {
    status?: number;
    message?: string | undefined;
    data?: TipoAsiento;
}

export interface TokenDto {
    token?: string | undefined;
    expiration?: Date;
}

export interface TokenDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: TokenDto;
}

export interface UsuarioActualDto {
    usuarioId?: number;
    usuario?: string | undefined;
    nombre?: string | undefined;
    apellido?: string | undefined;
    direccion?: string | undefined;
    ci?: string | undefined;
    email?: string | undefined;
    fechaNacimiento?: string | undefined;
    telefono?: string | undefined;
    roles?: RolDto[] | undefined;
}

export interface UsuarioActualDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: UsuarioActualDto;
}

export interface UsuarioDto {
    usuarioId?: number;
    usuario?: string | undefined;
    nombre?: string | undefined;
    apellido?: string | undefined;
    direccion?: string | undefined;
    ci?: string | undefined;
    email?: string | undefined;
    fechaNacimiento?: string | undefined;
    telefono?: string | undefined;
    roles?: string | undefined;
}

export interface UsuarioDtoListResponse {
    status?: number;
    message?: string | undefined;
    data?: UsuarioDto[] | undefined;
}

export interface UsuarioModificarDto {
    usuarioId?: number;
    usuario?: string | undefined;
    password?: string | undefined;
    roles?: number[] | undefined;
    habilitado?: boolean;
}

export interface UsuarioMostrarModificarDto {
    rolesUsuario?: RolesUsuario;
    roles?: RolDto[] | undefined;
}

export interface UsuarioMostrarModificarDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: UsuarioMostrarModificarDto;
}

export interface VAlmacen {
    id?: number;
    codigoAlmacen?: string | undefined;
    dirrecion?: string | undefined;
    nombreAlmacen?: string | undefined;
}

export interface VAlmacenListResponse {
    status?: number;
    message?: string | undefined;
    data?: VAlmacen[] | undefined;
}

export interface VAlmacenResponse {
    status?: number;
    message?: string | undefined;
    data?: VAlmacen;
}

export interface VMoneda {
    id?: number;
    nombreMoneda?: string | undefined;
}

export interface VPlanCuentas {
    id?: number;
    codigo?: string | undefined;
    nombreCuenta?: string | undefined;
    moneda?: string | undefined;
    valor?: number;
    codigoIdentificador?: string | undefined;
    nivel?: number;
    debe?: number;
    haber?: number;
    vPlanCuentaId?: number;
}

export interface VPlanCuentasListResponse {
    status?: number;
    message?: string | undefined;
    data?: VPlanCuentas[] | undefined;
}

export interface VPlanCuentasResponse {
    status?: number;
    message?: string | undefined;
    data?: VPlanCuentas;
}

export interface VProductoImagenes {
    id?: number;
    nombre?: string | undefined;
    vproductoId?: number;
}

export interface VProductoImagenesListResponse {
    status?: number;
    message?: string | undefined;
    data?: VProductoImagenes[] | undefined;
}

export interface VProveedor {
    id?: number;
    nit?: string | undefined;
    codigoProveedor?: string | undefined;
    nombreProveedor?: string | undefined;
    dirrecion?: string | undefined;
    telefono?: string | undefined;
    contacto?: string | undefined;
    planCuentaId?: number;
}

export interface VProveedorListResponse {
    status?: number;
    message?: string | undefined;
    data?: VProveedor[] | undefined;
}

export interface VProveedorResponse {
    status?: number;
    message?: string | undefined;
    data?: VProveedor;
}

export interface WeatherForecast {
    date?: Date;
    temperatureC?: number;
    temperatureF?: number;
    summary?: string | undefined;
}

export interface CuentasDto {
    id?: number;
    codigo?: string | undefined;
    nombreCuenta?: string | undefined;
    vPlanCuentaId?: number;
    asientoId?: number;
    rol?: string | undefined;
}

export interface PlanCuentaDto {
    id?: number;
    codigo?: string | undefined;
    nombreCuenta?: string | undefined;
    moneda?: string | undefined;
    valor?: number;
    codigoIdentificador?: string | undefined;
    nivel?: number;
    debe?: number;
    haber?: number;
    vPlanCuentaId?: number;
}

export interface RolesUsuario {
    usuarioId?: number;
    usuario?: string | undefined;
    roles?: RolDto[] | undefined;
    habilitado?: boolean;
}

export interface VentaDto {
    id?: number;
    fechaCreacion?: Date;
    descripcion?: string | undefined;
    nit?: string | undefined;
    telefono?: string | undefined;
    estado?: EstadoVenta;
    codigoVenta?: string | undefined;
    vCliente?: ClienteDto;
    montoliteral?: string | undefined;
    total?: number;
    asiento?: ListaAsientoDto;
    usuario?: string | undefined;
    productos?: VentaProductoDto[] | undefined;
}

export interface VentaDtoResponse {
    status?: number;
    message?: string | undefined;
    data?: VentaDto;
}

export interface VentaProductoDto {
    productoId?: number;
    cantidad?: number;
    codigoProducto?: string | undefined;
    nombreProducto?: string | undefined;
    precioUnitario?: number;
    precioTotal?: number;
}